### ISSUE TITLE
Cluster settings JSON namespace assumed to be flat

### ISSUE THREAD

**Issue by magnusbaeck** [anchor/elasticsearchadmin#4]
allocator_disabled() bails out with an error on Elasticsearch 1.3 since it assumes that the cluster settings namespace is flat, i.e. the settings key is found directly under the "transient" or "persistent" keys:

```
{
  "transient": {
    "cluster.routing.allocation.disable_allocation": true
  }
}
```

But in reality the results of /_cluster/settings looks like this:

```
{
  "transient": {
    "cluster": {
      "routing": {
        "allocation": {
          "disable_allocation": "false"
        }
      }
    }
  }
}
```

The es-allocator-disable and es-allocator-enable scripts do what they're supposed to do but the output looks like this and the exit code is 1:

```
[myhostname] [10601]: [INFO] Enabling automatic shard allocation...
[myhostname] [10601]: [INFO] Old status: UNKNOWN
[myhostname] [10601]: [INFO] New status: UNKNOWN
Traceback (most recent call last):
  File "/usr/bin/es-allocator-enable", line 112, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/es-allocator-enable", line 101, in main
    assert new_status == "enabled"
AssertionError
```

By the looks of it there's a similar problem with get_index_translog_disable_flush().

**Comment by magnusbaeck** [comment]
Oops, forgot to close this bug when PR #5 was merged last week.
